
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="css/myStyle.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kryspin Kwasny</title>
</head>

<nav>
<div class="row">
    <div class="col-md-12">
        <div id="header" style="width: 100%">

            <ul class="center">

                <a href=""<li class="">HOME</li></a>
                <a href=""<li class="">PORTFOLIO</li></a>
                <a href=""<li class="">Contact Me</li></a>
            <!--    <li id="Javascript" style="float: right; font-size: 10px">Javascript
                <p id="time">Current Time</p> -->
                </li>
            </ul>



        </div>
    </div>
</div>
</nav>

<script>
  //  var today = new Date();
  //  var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
  //  document.getElementById("time").innerHTML = "Current Time - " + time;
</script>