<?php require("header.phtml"); ?>

<body>
<div class="TopPhotoContainer">
    <div class="row">
        <div class="col-md-12">
            <div id="topPhotoContent">
                <img src="image/placeHolderPP.jpg" class="imageContainer">
                <p class="textCenter">Hey, I'm</p>
                <p class="textCenterLower">-<?php echo $view->title ?>-</p>
            </div>
        </div>
    </div>
</div>

<div style="background: lightgray; padding-top: 10px">

    <div class="row">
    <div class="col-md-12">
            <!-- About Me Section -->
            <h1 id="aboutMe"> About Me </h1>
    </div>
    </div>

    <div class="row">
    <div class="col-md-6">

        <h3 style="margin-left: 2%">Who I'm I?</h3>

        <p style="margin-left: 2%">My name is <b>Kryspin Kwasny</b> and I'm currently studying at the <a href="https://www.salford.ac.uk/" style="padding-left: 0; padding-top: 0">University of Salford</a><br>
           I've successfully compeleted both 1st and 2nd Year and im moving onto the 3rd. <br>

            Ive learned all sorts of different things that help me prepeare for the <abbr title="Computer Science" style="text-decoration: none">CS</abbr> / <abbr title="Software Engineering" style="text-decoration: none">SE</abbr> industy


        </p>



    </div>
        <div class="col-md-6">

        <h3> Module's Taught </h3>
            <ul>

                <div class="col-md-3" style="display: inline-block; margin-right: 10px; vertical-align: top">
                <li class="displayBlock"><h5>Year 1</h5></li>
                <li class="displayBlock">Programming One</li>
                <li class="displayBlock">Programming Two</li>
                <li class="displayBlock">Database Systems</li>
                <li class="displayBlock"><abbr title="Proffessional Development Practices" style="text-decoration: none">PDP</abbr></li>
                </div>

                <div class="col-md-3" style="display: inline-block; margin-left: 10px; margin-right: 10px">
                    <li class="displayBlock"><h5>Year 2</h5></li>
                    <li class="displayBlock">Programming One</li>
                    <li class="displayBlock">Programming Two</li>
                    <li class="displayBlock">Database Systems</li>
                    <li class="displayBlock"><abbr title="Proffessional Development Practices" style="text-decoration: none">PDP</abbr></li>
                </div>

                <div class="col-md-3" style="display: inline-block; margin-left: 10px; vertical-align: top;">
                    <li class="displayBlock"><h5>Year 2</h5></li>
                    <li class="displayBlock">Programming One</li>
                    <li class="displayBlock">Programming Two</li>
                    <li class="displayBlock">Database Systems</li>
                    <li class="displayBlock"><abbr title="Proffessional Development Practices" style="text-decoration: none">PDP</abbr></li>
                </div>

            </ul>

        </div>
    </div>


</div>


</body>

<?php require("footer.phtml")?>
