<?php require("header.phtml"); ?>

<script src="js/ImageSlider.js"></script>

<body onload="checkPage()">
<div class="TopPhotoContainer">
    <div class="row">
        <div class="col-md-12">
            <div id="topPhotoContent">
                <img  id="LiveImage" src="image/placeHolderPP.jpg" class="imageContainer">
                    <div>
                    <button onclick="Nxt()" id="btnNxt"> > </button>
                    <button onclick="Prev()" id="btnPrev"> < </button>
                     </div>
                <p class="textCenter" id="LiveText">Hey, I'm</p>
                <p class="textCenterLower" id="LiveText2">-<?php echo $view->title ?>-</p>
            </div>
        </div>
    </div>
</div>

<div id="MainBodyContainer">

    <div class="row">
    <div class="col-md-12">
            <!-- About Me Section -->
            <h1 id="aboutMe"> About Me </h1>
    </div>
    </div>

    <div class="row">
    <div class="col-md-6" style="border-right-style: solid; border-color: dimgray">

        <h3 style="margin-left: 2%">Who I'm I?</h3>

        <p style="margin-left: 2%">My name is <b>Kryspin Kwasny</b> and I'm currently studying at the <a href="https://www.salford.ac.uk/" style="padding-left: 0; padding-top: 0">University of Salford</a><br>
           I've successfully compeleted both 1st and 2nd Year and im moving onto the 3rd. <br>

            Ive learned all sorts of different things that help me prepeare for the <abbr title="Computer Science" style="text-decoration: none">CS</abbr> / <abbr title="Software Engineering" style="text-decoration: none">SE</abbr> industy


        </p>



    </div>
        <div class="col-md-6">

        <h3 id="ModulesTaughtHeading"> Module's Taught </h3>
            <ul>

                <div class="col-md-3" id="Y1">
                <li class="displayBlock"><h5>Year 1</h5></li>
                <li class="displayBlock">Programming One</li>
                <li class="displayBlock">Programming Two</li>
                <li class="displayBlock">Database Systems</li>
                <li class="displayBlock">Computer System Internals and Linux</li>
                <li class="displayBlock">WebDevelopment & <abbr title="Human Computer Interface">HCI</abbr></li>
                <li class="displayBlock"><abbr title="Proffessional Development Practices" style="text-decoration: none">PDP</abbr></li>
                </div>

                <div class="col-md-3" id="Y2">
                    <li class="displayBlock"><h5>Year 2</h5></li>
                    <li class="displayBlock" >Career Development</li>
                    <li class="displayBlock">Client Server Systems</li>
                    <li class="displayBlock">Data Structure & Algorithms</li>
                    <li class="displayBlock">Design Pattern</li>
                    <li class="displayBlock">Networking & Security</li>
                    <li class="displayBlock">Software Evolution</li>
                    <li class="displayBlock">Software Projects & Agile Techniques </li>
                </div>

                <div class="col-md-3" id="Y3">
                    <li class="displayBlock"><h5>Year 3</h5></li>
                    <li class="displayBlock">Dependable <abbr title="Software Engineering"><b>SE</b></abbr></li>
                    <li class="displayBlock">Project for <abbr title="Software Engineering"><b>SE</b></abbr></li>
                    <li class="displayBlock">Software Quality</li>
                    <li class="displayBlock"><abbr title="Virtual Reality">VR</abbr> and 3D games</li>
                    <li class="displayBlock">Mobile Development</li>
                </div>

            </ul>

        </div>
    </div>


</div>

</body>






<?php require("footer.phtml")?>
